### ISSUE TITLE
matmul failed to build kernel after servel executions on both OpenCL and CUDA backend.

### ISSUE THREAD

**Issue by marty1885** [arrayfire/arrayfire#2089]
Hi! I'm implementing deep learning algorithms in ArrayFire and I ran into problems when executing Dense(FC) layers.

I wrote a function that executes the forward pass of a FC layer.
```C++
af::array = af::transpose(af::matmulTT(x, w)) + b;
```
I use matmulTT because I originally wrote my code using xtensor, thus the data is in C order.

When using either the OpenCL or the CUDA backend. Passing lots of `af::array` as x to the function makes it runs slower and slower. Then eventually AF throws an exception

CUDA:
```
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::__cxx11::string)
In file src/backend/cuda/jit.cpp:336
CU Error (200)


In function af::array af::matmulTT(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:44
```

OpenCL:
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
OpenCL Error (-9999): Unknown OpenCL Error (-9999) when calling clBuildProgram
In function af::array af::matmulTT(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:44
```
But this does not happen with the CPU backend. 
I've also tested the unified backend to test and encounters the same behaviour. OpenCL and CUDA crashes but the CPU backend works.

Many thanks.

Tested on NVIDIA GTX 970, Manjaro Linux 64bits, driver 390.25

**Comment by umar456** [comment]
Those are odd error values. cuError(200) is an error that pops up with you are compiling with an invalid module. We use the CUDA device properties to get the compute capability.

Can you run the deviceQuery example provided by the CUDA Toolkit? If you are building ArrayFire from source I would be interested in the value of the `arch` variable after this call:

https://github.com/arrayfire/arrayfire/blob/master/src/backend/cuda/jit.cpp#L282

you can print it by running this command afterwards:

```
printf("arch flags: %s\n", arch.data());
```

The -9999 error pops up when you have an out of bound memory access. Do you have any custom kernels in your application? I can't imagine why matmul would be accessing memory out of bounds.

**Comment by marty1885** [comment]
It's pure ArrayFire code.

The output of deviceQuery
https://gist.github.com/marty1885/058ac742c481e3a3ffdd1aaa4f3a0804

Also here is the output of clinfo:
https://gist.github.com/marty1885/01b1da0927d3cea2cdfa3b5ca99961d3

Also the function runs slower and slower.  It is reasonable for the first batch to be slower due to compiling kernels. But why it gets slower over timer?
Like so
```
(Traning a MLP)
Time per batch 1.04186 seconds.
Time per batch 0.331423 seconds.
Time per batch 0.235584 seconds.
Time per batch 0.242835 seconds.
Time per batch 0.251447 seconds.
Time per batch 0.258243 seconds.
Time per batch 0.266202 seconds.
Time per batch 0.272865 seconds.
Time per batch 0.281923 seconds.
Time per batch 0.289188 seconds.
Time per batch 0.298467 seconds.
Time per batch 0.307164 seconds.
Time per batch 0.315158 seconds.
Time per batch 0.325835 seconds.
Time per batch 0.335516 seconds.
Time per batch 0.341608 seconds.
Time per batch 0.351986 seconds.
Time per batch 0.368721 seconds.
Time per batch 0.371536 seconds.
Time per batch 0.381199 seconds.
Time per batch 0.392553 seconds.
Time per batch 0.401055 seconds.
Time per batch 0.414397 seconds.
Time per batch 0.424162 seconds.
Time per batch 0.435402 seconds.
Time per batch 0.449679 seconds.
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::__cxx11::string)
In file src/backend/cuda/jit.cpp:336
CU Error (200)


In function af::array af::matmulTT(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:44

```

I install AF using pacman and I failed to build AF from source. The CUDA backend is complaining about having GCC begin too new.

**Comment by 9prady9** [comment]
@marty1885 Regarding GCC being too new on Arch, CUDA toolkit 9.1 has suport GCC 6.x only so far. Thus, you would have to install that and do the following in your `.bashrc` for CMake to pick up the right compilers - this is what I do on my Arch too.

```
export CC=/usr/bin/gcc-6
export CXX=/usr/bin/g++-6
```

**Comment by marty1885** [comment]
I got this from the added line. `arch flags: --gpu-architecture=compute_52`

**Comment by 9prady9** [comment]
The compute version sounds correct - GTX 970 's compute version is 5.2. Did you try building CUDA backend from source ?

**Comment by umar456** [comment]
I think this may have been an issue with the non-linear JIT kernels. This has been fixed in #2127. @marty1885 can you try the latest master?

**Comment by marty1885** [comment]
@umar456 I pulled from master and did a fresh build serval times. But  `make install` failed every time with this. 
Is installation part broken?
```
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/home/marty/Documents/arrayfire/build/third_party/forge/lib".
```

**Comment by 9prady9** [comment]
Can you please tell what are the contents of 'third_party/forge' folder?

**Comment by marty1885** [comment]
Sorry for the delay. 
ls: `third_party/forge`: No such file or directory
And the error does not go away even if I turn building docs off.

**Comment by marty1885** [comment]
@FloopCZ Weird..... I checked that `make` successfully built everything. And `-DAF_WITH_GRAPHICS=off`doesn't fix the problem. ArrayFire still wants to install forge for some reason.

**Comment by marty1885** [comment]
Okay, so creating `forge/lib` manually clears the problem.
@umar456 No, The latest master branch still has the problem. I get:
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::kc_entry_t cuda::compileKernel(const char*, std::__cxx11::string)
In file src/backend/cuda/jit.cpp:334
CU Error (200)


In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:922
```

**Comment by FloopCZ** [comment]
> DAF_WITH_GRAPHICS=offdoesn't fix the problem. ArrayFire still wants to install forge for some reason.

That is strange, it does not happen to me.

Btw, I suppose you have already done this, but just to be sure that the linker picked up your newly built AF library: Have you run `ldconfig` after installation and have you checked the output of `af::info()` or `ldd your_program`?

**Comment by marty1885** [comment]
Yeah, `ldd` shows that my program is linked to the newly built AF.

----
I found something even weirder. If I turn address sanitizer on; trying to debug whats happening in my program. ArrayFire throws an OOM exception upon creating an `array`. I can really make use of more precise information inside AF's exception message.
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function af_err af_randn(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/random.cpp:335
```

I'm trying to make a minimal example, but it will take a while.

**Comment by umar456** [comment]
Hey @marty1885, Could I get access to the code somehow? You can send it to me directly if you don't want to post it publicly.

**Comment by marty1885** [comment]
@umar456 I've no problem publishing it. It is a open source project. :smile:  But the amount of code it has is way too large for me to say "here it is, please find the problem".

Anyway, here is it and you'll need a C++14 compile ,`xtensor` and `nlohmann/json` with multi header enabled to build it.
https://github.com/marty1885/Athena

**Comment by umar456** [comment]
@marty1885 I haven't been able to reproduce it with the latest master. I am running on a 750M on my MacBook.

**Comment by marty1885** [comment]
@umar456 I've tried on a 850M (basiclly 750M) and a 780Ti on Linux and it does not occur. May it be a problem strictly on the GeForce 900 Series GPU?

**Comment by 9prady9** [comment]
@marty1885 Is this still an active issue ?

**Comment by marty1885** [comment]
@marty1885 I eventually moved to building my own tensor library and didn't figure out why. Closing
