### ISSUE TITLE
af::inverse CUDA error

### ISSUE THREAD

**Issue by guatavita** [arrayfire/arrayfire#2468]
Hello,

I recently changed my GPU from a Quadro M2000, 4096 MB (CUDA Compute 5.2) to a GeForce GTX 1080 Ti, 11264 MB (CUDA Compute 6.1) to have more speed and less memory limitation.

I am trying to run a previously validated algorithm on "bigger" data but I am experiencing a CUDA error, the screen goes black and all GPU application crashes.

ArrayFire v3.6.2 (CUDA, 64-bit Windows, build dc38ef13)
Platform: CUDA Toolkit 10, Driver: CUDA Driver Version: 10010
[0] GeForce GTX 1080 Ti, 11264 MB, CUDA Compute 6.1
Nvidia 3D Vision Controller Driver 390.41 
Nvidia 3D Vision Driver 419.35
Nvidia Graphics Driver 419.35
Nvidia CUDA Development 9.1 (not using it but it is installed)

I can reproduce the error using this simple code, the error occurs randomly regardless of the size, but, seems to be systematic with large array (N>5000).

```
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

void function();

int main(int argc, char *argv[])
{
  try {
    // Select a device and display arrayfire info
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    for (int i = 0; i < 1000; i++) {
      function();
    }
  }
  catch (af::exception& e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }
  return 0;
}

void function() {
  int N = 2000;
  int D = 3;
  af::array ones = constant(1, N, f32);
  af::array rand1 = randu(N, D, f32);
  af::array q2 = randu(N, N - D - 1, f32);  // size is [N][N-D-1]  
  af::array K = randu(N, N, f32);  // size is [N][N-D-1]  
  af::array id1 = 0.001 * af::identity(N - D - 1, N - D - 1, f32);
  af::array T = join(1, ones, rand1);
  af::array gamma = matmul(inverse(matmul(matmul(q2, K, AF_MAT_TRANS), q2) + id1), matmul(q2, T, AF_MAT_TRANS));
}
```

```
ArrayFire Exception (Internal error:998):
In function struct cusolverDnContext *__cdecl cuda::solverDnHandle(void)
In file src\backend\cuda\platform.cpp:487
CUDA Error (4): unspecified launch failure

In function class af::array __cdecl af::inverse(const class af::array &,const af_mat_prop)
In file src\api\cpp\lapack.cpp:116
```

Someone has an idea of what can cause this error? The only thing I changed that cause this error is my GPU and my Nvidia drivers. The arrayfire code is still the same.

Thank you!

Edit: by adding "af::sync();" after the function call i got the following error (also after few iterations): 

```
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::sync(int)
In file src\backend\cuda\platform.cpp:642
CUDA Error (4): unspecified launch failure

In function void __cdecl af::sync(const int)
In file src\api\cpp\device.cpp:115
```

**Comment by guatavita** [comment]
Update.

I uninstall my Nvidia drivers using the DDU software (from wagnardsoft) and did a clean install of the Nvidia Graphics Driver 419.67. Reboot and tried to stress the GPU again with the small code from the previous post. 

The error is still happening.

However, I did notice that the error happen more often when i run the code without af::sync() after calling the function.

**Comment by guatavita** [comment]
Tried to run a cuda-memcheck but I don't know if this is gonna help...

```
========= CUDA-MEMCHECK
ArrayFire v3.6.2 (CUDA, 64-bit Windows, build dc38ef13)
Platform: CUDA Toolkit 10, Driver: CUDA Driver Version: 10010
[0] GeForce GTX 1080 Ti, 11264 MB, CUDA Compute 6.1
0%
ArrayFire Exception (Internal error:998):
In function void *__cdecl cuda::MemoryManager::nativeAlloc(const unsigned __int64)
In file src\backend\cuda\memory.cpp:191
CUDA Error (4): unspecified launch failure


In function class af::array __cdecl af::identity(const class af::dim4 &,const af_dtype)
In file src\api\cpp\data.cpp:155
========= Internal Memcheck Error: Out of device memory
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:C:\Windows\SYSTEM32\nvcuda.dll (cuMemcpy2DAsync + 0x1b9ff9) [0x1c8735]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x37a49) [0x83bfc]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x1d4c1) [0x69674]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x154baab) [0x1597c5e]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x154aef1) [0x15970a4]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x1548fe8) [0x159519b]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x154636f) [0x1592522]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x214ac18) [0x2196dcb]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x214e287) [0x219a43a]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x2310868) [0x235ca1b]
=========     Host Frame:c:\program files\arrayfire\v3.6\lib\afcuda.dll (af::array::array_proxy::device<__int64> + 0x2310f88) [0x235d13b]
=========     Host Frame:C:\Bastien\DEV\Arrayfire_example\bin\Release\qr_cuda.exe [0x1300]
=========     Host Frame:C:\Bastien\DEV\Arrayfire_example\bin\Release\qr_cuda.exe [0x1579]
=========     Host Frame:C:\Bastien\DEV\Arrayfire_example\bin\Release\qr_cuda.exe [0x17b8]
=========     Host Frame:C:\Windows\System32\KERNEL32.DLL (BaseThreadInitThunk + 0x14) [0x11fe4]
=========     Host Frame:C:\Windows\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x21) [0x6cb81]
=========
========= ERROR SUMMARY: 1 error
```

**Comment by 9prady9** [comment]
I have a GTX 1060 with Driver version 418.56, although I have CUDA 10.1(I don't think that is the cause unless something was fixed in cuSolver itself).

My GPU has just 3GB and the code snippet finished execution without segfaults or out of memory exception. Have you tried printing the memory usage information at end of each iteration using `AF_MEM_INFO` macro defined in `include/af/macros.h` ?

**Comment by guatavita** [comment]
I added the AF_MEM_INFO macro at each iteration. Same stuff, memory is stable. Here is what i got for each iteration with a crash at 5.98% (10000 iterations and N=6000): 

```
AF Memory at c:\bastien\dev\arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ 1295073280 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
5.98%
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::sync(int)
In file src\backend\cuda\platform.cpp:642
CUDA Error (4): unspecified launch failure

In function void __cdecl af::sync(const int)
In file src\api\cpp\device.cpp:115
```

I don't know if the GPU is running at high temperature and there is maybe a safety that cut everything. Is that possible and throw such error? Again, my two monitors go black for 1-2s and every GPU applications crash.

**Comment by guatavita** [comment]
Update, changing N=10000 gave me a negative output..

```
ArrayFire v3.6.2 (CUDA, 64-bit Windows, build dc38ef13)
Platform: CUDA Toolkit 10, Driver: CUDA Driver Version: 10010
[0] GeForce GTX 1080 Ti, 11264 MB, CUDA Compute 6.1
0%
AF Memory at c:\bastien\dev\arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ -696516608 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
0.01%
AF Memory at c:\bastien\dev\arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ -696516608 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
0.02%
```

**Comment by 9prady9** [comment]
You shouldn't need to re-install ArrayFire, we don't do any registry magic at all.

Can you try the following environment variable set to 1
http://arrayfire.org/docs/configuring_environment.htm#af_synchronous_calls

That should synchronize all function calls, that should help narrow it down a bit.

**Comment by guatavita** [comment]
I tried to recompile the code with the following variable in CMake:
`set(ENV{AF_SYNCHRONOUS_CALLS} 1)
`
However, i am not sure if this is the right way to configure the environment variable. If this is the right way, I still have the same error. 

```
AF Memory at c:\bastien\dev\arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ 3598450688 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
0.37%
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::sync(int)
In file src\backend\cuda\platform.cpp:642
CUDA Error (4): unspecified launch failure
In function void __cdecl af::sync(const int)
In file src\api\cpp\device.cpp:115
```

I finished 10000 iterations without error and N=4000 with the environment variable at 1. However, regardless of the environment variable, it still crash with larger array.

**Comment by 9prady9** [comment]
It is not a cmake variable. On Windows, you have set either in command prompt, powershell or change it from GUI.

For command prompt: `setx AF_SYNCHRONOUS_CALLS "1"`
For powershell: `$env:AF_SYNCHRONOUS_CALLS = 1`
GUI: [link](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by guatavita** [comment]
Ok I changed the system variable to 1. I have exactly the same error:

```
AF Memory at c:\bastien\dev\arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ 3598450688 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
0.89%
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::sync(int)
In file src\backend\cuda\platform.cpp:642
CUDA Error (4): unspecified launch failure

In function void __cdecl af::sync(const int)
In file src\api\cpp\device.cpp:115
```

**Comment by 9prady9** [comment]
Okay, please give me some time, I will run this program on Windows and get back to you. I am unable to reproduce this on linux at the moment.

**Comment by guatavita** [comment]
I am running my algorithm on multiple data, here is the error I recorded during computation, i can not share the code however.

The error happened more than 10 times leading to a freeze of the computer for 3s, black screen and crash of the executable. 

```
ArrayFire Exception (Internal error:998):
In function void cuda::kernel::identity<T>(cuda::Param<T>)
In file src\backend\cuda\kernel/identity.hpp:62
CUDA Error (4): unspecified launch failure
In function class af::array __cdecl af::identity(const class af::dim4 &,const af_dtype)
In file src\api\cpp\data.cpp:155
```

Do you think it can come from my hardware or Windows10 drivers?

**Comment by 9prady9** [comment]
I am building the code on windows as I write here, we should know shortly if it is windows issue. Which version of Nvidia driver you have?

**Comment by guatavita** [comment]
I have the Nvidia Graphics Driver 419.67 creative version.

The codes were working with my previous GPU. Crashes during test code and code from my algorithm that I am using are only happening since GPU/driver upgrade.

**Comment by 9prady9** [comment]
That's the driver I have too. My windows is doing updates, so it is taking more time than I expected. I will leave an update here once I have something to share.

**Comment by 9prady9** [comment]
No crash on Windows either for me with N =6k using GTX 1060, this on master branch. May be some issue which is present in 3.6.2 was fixed later in master. I am checking it out on 3.6.2 tag at the moment.

**Comment by guatavita** [comment]
Ok if there is no crashes on your side with AF 3.6.2, I will try to reinstall a clean version of Windows 10 with the new GPU installed.

**Comment by 9prady9** [comment]
Unfortunately, I haven't been able to get a crash/segfault for even with 3.6.2 for N=6k.

**Comment by guatavita** [comment]
Ok, I will try to do a clean install to see if the error persist after. I will update this thread.

**Comment by guatavita** [comment]
Hello, 

It took some time to get my computer reinstalled with a fresh version of Windows 10. However, I still have the same trouble... :( 

One the last test, the only difference here is that the screen is not going black but just quickly freeze.

I have the same configuration, NVIDIA Driver v419.67. I only installed Windows 10, visual studio 16 2019, and arrayfire 3.6.2. 

> ArrayFire v3.6.2 (CUDA, 64-bit Windows, build dc38ef13)
> Platform: CUDA Toolkit 10, Driver: CUDA Driver Version: 10010
> [0] GeForce GTX 1080 Ti, 11264 MB, CUDA Compute 6.1
> 
> ArrayFire Exception (Internal error:998):
> In function void __cdecl cuda::sync(int)
> In file src\backend\cuda\platform.cpp:642
> CUDA Error (4): unspecified launch failure
> 
> In function void __cdecl af::sync(const int)
> In file src\api\cpp\device.cpp:115

This is my professional machine and I cannot work with that right now. The cause of such problem could come from the GPU and I should consider contacting the seller? 

I could ask a colleague to train a deep learning model on my GPU to see if we have trouble with other library?

**Comment by guatavita** [comment]
I suspected a temperature increase but the GPU is around 70C when stressed. The code crashes even with the computer case open. 

I also suspected the power supply unit, but i have a 1300W PSU on my Dell Precision Tower 7910 and i have a 6- and 8-pins cable power for the GPU...

I did a "Unigine Heaven Benchmark 4.0 (basic edition)" and it runs smoothly. However, running the benchmark while running the Arrayfire program crashed after few seconds.

**Comment by 9prady9** [comment]
I think hardware failures are rare, but I have seen fair share of them. So, if you can run the same code on another GPU in the same system, then we will know for sure if it is ArrayFire or GPU.

**Comment by guatavita** [comment]
The code was running fine with my previous M2000 and with the P5000 of a colleague. I think the problem is coming from my actual configuration (mix of the GPU/hardware/system and AF). 

What do you mean by GPU trial?

I am currently installing Arrayfire from the Github sources. I finished to install all the requirement from VCPKG and CUDA 10.1. Will give an update.

**Comment by 9prady9** [comment]
Please ignore that line. I was suggesting a driver downgrade and check if that fixes the problem.

**Comment by guatavita** [comment]
I am unable to use Arrayfire from the github sources.

I installed everything following https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Windows.

Everything runs smoothly, i build the release of AF with MSVC 16 2019 with -tv140 in x64, eveything build in MSVC (using MSVC 2015 v140 compiler). I got a "Build: 2 succeeded, 0 failed, 494 up-to-date, 0 skipped ==========" without OPEN_CL.

When i try to build a small project using the built sources i have the following cmake error:

> CMake Error at C:/Bastien/DEV/arrayfire/bin/ArrayFireConfig.cmake:131 (get_property):
>   get_property given invalid argument "RELEASE".
> Call Stack (most recent call first):
>   CMakeLists.txt:13 (find_package)

Trying to launch the hello_world_cpu.exe or hello_world_cuda.exe from the MSVC release folder gave me an error saying that the afcpu.dll or afcuda.dll are not found.

I added the following in the environment variable. Same error...
AF_PATH=C:\Bastien\DEV\arrayfire
AF_PATH_v3=C:\Bastien\DEV\arrayfire

In Path -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\nvvm\bin; C:\Bastien\DEV\arrayfire\bin\bin\Release; C:\Bastien\DEV\arrayfire; C:\Bastien\DEV\arrayfire\bin

Any idea for me to be able to test this version of Arrayfire before downgrading the Nvidia drivers?

**Comment by umar456** [comment]
Hey @guatavita, Could you join us on our slack channel. I think that is the right platform for this conversation. We can have a better discussion there.

**Comment by guatavita** [comment]
Plz ignore my last message. I am able to run the AF .exe's from my release. I just needed to log off/on to update the path of my W10. 

Working on it tonight or tomorrow. Will update.

**Comment by guatavita** [comment]
Cmake project outside the sources are compiling too, i needed to put "C:\Bastien\DEV\arrayfire\bin\bin\Release" for the AF_DIR. I did not know that... 

I will be able to run my "GPU stress code" with the latest AF version. I am leaving the office, it as been 13h. I will see if the GPU crashed or not from home and update with a message.

**Comment by guatavita** [comment]
Update:

Using the source code of AF from Github to build the small project to stress the code. I have the same crash: 

```
AF Memory at C:\Bastien\DEV\Arrayfire_example\qr.cpp:44:
Allocated [ Bytes | Buffers ] = [ 1295073280 | 17 ]
In Use    [ Bytes | Buffers ] = [ 0 | 0 ]
0.15%
ArrayFire Exception (Internal error:998):
In function void __cdecl cuda::sync(int)
In file src\backend\cuda\platform.cpp:803
CUDA Error (719): unspecified launch failure

In function void __cdecl af::sync(const int)
In file src\api\cpp\device.cpp:95
```

I will try to downgrade the Nvidia drivers tomorrow to see if i have the same problem.

**Comment by guatavita** [comment]
I downgraded to 411.63 to build the project with AF 3.6.2. 

I am currently running the code to see if it crashes and so far it does not seems to crash... 

The only difference between the two is the CUDA Driver Version

NO CRASH : 10000
CRASH : 10010

The other stuff are the same

ArrayFire v3.6.2 (CUDA, 64-bit Windows, build dc38ef13)
Platform: CUDA Toolkit 10
GeForce GTX 1080 Ti, 11264 MB, CUDA Compute 6.1

**Comment by guatavita** [comment]
Also crashed after 3000 iterations when removing the GIGABYTE boost and monitoring the GPU load <=99%.

No more idea, sending a message for warranty. Thank you @9prady9 and @umar456 for the help/advice.
