### ISSUE TITLE
ArrayFire Python Import Freezes with new OpenCL Intel Driver

### ISSUE THREAD

**Issue by dhaverporth** [arrayfire/arrayfire#2493]
Please see this [issue](https://github.com/arrayfire/arrayfire/issues/2482) for additional context.  Previously I had an issue with loading opencl for our Intel processors.  It turned out that the Intel OpenCL driver that we were using was too old (2016 driver) and the Intel Processors we were using were released in 2017.  The new Intel driver that we installed was released in March of 2019 and the version number is 18.1.0.014.  When we installed the new driver we fixed the errors that we saw in clinfo with OpenCL not being able to see the processors; however, when we installed the new drivers ArrayFire is no longer able to import in Python.  Previously we were able to import ArrayFire but had an error when we tried to execute `af.set_backend('opencl')` but now we are unable to import at all.  We performed an strace on the Python process and saw that the program got hung up on "futex" command.  A "futex" apparently occurs when a program is waiting for something to happen; so apparently the program is waiting for some input but is not receiving any.  One thing that I did notice is that with the new driver is that the version of OpenCL shown in clinfo went from 1.2 to 2.1.  

Would it be possible for you to verify that the Intel OpenCL Driver 18.1.0.014 works in your copy of ArrayFire?

**Comment by 9prady9** [comment]
A quick question to you, did you try running the C++ helloworld example that ships with ArrayFire ? If you haven't already, can you please try it out and let us know how does the af::info output look like in the C++ example ? Does it show Intel CPU ?

**Comment by dhaverporth** [comment]
@9prady9 :  When I tried compiling the helloworld example using cmake it gave the following error:

> Cmake Error at /opt/arrayfire/share/ArrayFire/cmake/ArrayFireUnifiedTargets.cmake:74
>The imported target "Arrayfire::af" references the file:  /opt/arrayfire/lib/libaf.so.3.6.1
>but this file does not exist

Indeed libaf.so.3.6.1 is not in that location but is in /usr/local/bin/arrayfire/lib/libaf.so.3.6.1.  I tried cmake on the /usr/local/bin/arrayfire/share/ArrayFire directory.  Should my system admins have installed arrayfire in the /opt/ directory?  The AF_PATH is set to /usr/local/bin/arrayfire/include.

**Comment by umar456** [comment]
This is strange. It looks like the cmake files were installed in the /opt directory but the libs are installed in /usr/local/bin. How was the library installed? I think Slack is a better platform for this type of issue.

**Comment by dhaverporth** [comment]
@umar456 :  Actually the cmake files are located in both /opt and /usr/local/bin.  I installed the cmake C++ code first in the /usr/local/bin and then when I decided I wanted to use the Python wrapper, installed arrayfire using PIP.  Is it possible that pip installed a second version of Arrayfire in the /opt directory?

**Comment by 9prady9** [comment]
It looks like there are two versions of arrayfire installed in two different locations.

On a side note, we released 3.6.3 yesterday. You should upgrade to latest release of possible. It has lot of fixes and improvements compared w.r.t 3.6.1

**Comment by dhaverporth** [comment]
I am not sure how the /opt/arrayfire installation got there but I deleted it and I am now able to get the helloworld to compile and work.  I can confirm that OpenCL is now seeing and using the Intel Processors so the previous issue is definitely resolved.  However, I am still not able to import the arrayfire Python module.  A question for you.  If I install the new version, do I have to reinstall the python bindings using PIP?

**Comment by dhaverporth** [comment]
OK I installed the 3.6.3 release but when I try to import arrayfire in python I am getting the following error:

> Error in "python3.6': free(): invalid pointer

It seems that ArrayFire might be trying to free memory that has already been cleared.  There is a long backtrace also produced but since that computer is not connected to the internet I cannot copy and paste.

**Comment by 9prady9** [comment]
@dhaverporth I am not really sure whats going in python-wrapper. A better person to help you with that quickly would be the wrapper's maintainer @pavanky .

Having said that, didn't the python import freeze even before upgrading to 3.6.3 per your comments. So, it may be something else that is causing it. Did you try a very simple example that just has the following ?
```
af.info()
```
Does that also freeze ?

Based on my past experience and what I heard from my peers, it is best to use `pipenv` to setup python in a virtualenv so that it doesn't conflict with any other python installations on that system.

**Comment by raulbocanegra** [comment]
Hi! I am experiencing the same on Ubuntu 18.04.
I have installed arrayfire 3.6.2 on `/opt`, copile and run the tests correctly on cpu and opencl backends (cuda not supported), then `pip install arrayfire`.
When I run python and do `import arrayfire as af` it freezes and I can't use it.

**Comment by 9prady9** [comment]
Is the behavior similar with 3.6.4 release also ?

**Comment by raulbocanegra** [comment]
If I remove 3.6.2 installation and install 3.6.4 the module is imported without freezing.

**Comment by 9prady9** [comment]
That is good. Is there any limitation on your end that's preventing 3.6.4 usage ?

**Comment by 9prady9** [comment]
Issues seems to be resolved per https://github.com/arrayfire/arrayfire-python/issues/215

closing due to inactivity and the above.
